### ISSUE TITLE
No Denpendancy install

### ISSUE THREAD

**Issue by Snoiteandthesv3ndwarves** [HugoTini/DeepBump#54]
Love the add-on. I wish other images could be baked so easily. But it does look like dependancies can't be found For Blender 5.1.

<img width="35780" height="2048" alt="Image" src="https://github.com/user-attachments/assets/1e9a0045-9528-4efb-ada1-4e8d20fad302" />

**Comment by ath0rus** [comment]
Adding to this, I just installed 5.1 and am doing a clean install of Blender, Downloaded the zip and when I went to add dependencies I got this error

`Dependency install issue : CompletedProcess(args=['C:\\Program Files\\Blender Foundation\\Blender 5.1\\5.1\\python\\bin\\python.exe', '-m', 'pip', 'install', 'onnxruntime==1.15.1', '-t', 'C:\\Users\\user\\AppData\\Roaming\\Blender Foundation\\Blender\\5.1\\scripts\\addons\\DeepBump-8\\dependencies'], returncode=1, stdout='', stderr='ERROR: Could not find a version that satisfies the requirement onnxruntime==1.15.1 (from versions: 1.20.0, 1.20.1, 1.21.0, 1.21.1, 1.22.0, 1.22.1, 1.23.0, 1.23.1, 1.23.2, 1.24.1, 1.24.2, 1.24.3, 1.24.4)\n\n[notice] A new release of pip is available: 25.2 -> 26.0.1\n[notice] To update, run: C:\\Program Files\\Blender Foundation\\Blender 5.1\\5.1\\python\\bin\\python.exe -m pip install --upgrade pip\nERROR: No matching distribution found for onnxruntime==1.15.1\n')
`

**Comment by Snoiteandthesv3ndwarves** [comment]
Thank you very much for your reply.
?. What does this mean I should do? Since 4.5 works Fine.

**Comment by LiJT** [comment]
> Thank you very much for your reply.
> ?. What does this mean I should do? Since 4.5 works Fine.
> […](#)

Hey man, 
DeepBump-8 need a dependency upgrade, since Blender 5.1 update to Python 3.13, onnxruntime no longer worked with Blender default python

ImportError: DLL load failed while importing onnxruntime_pybind11_state: cannot find module

**Comment by ath0rus** [comment]
> What does this mean I should do? Since 4.5 works Fine.

It works in 5.0.1 (I was using it the other day). We just have to wait it out for someone to make an update or @HugoTini updates it

**Comment by ValentinN84** [comment]
I can confirm DeepBump V8 works in Blender 5.0.1 but not in Blender 5.1.0.
In Blender 5.1.0 I've tried copying the dependencies from the old install but they do not get recognized in the addon preferences. Clicking on Install Dependencies in this state, with the old dependencies in the addon directory results in Blender freezing.
Installing DeepBump from scratch in Blender 5.1.0 gives the error mentioned by ath0rus above.
Upgrading PIP as the error suggests does not work, the same onnxruntime error persists after that.

**Comment by Snoiteandthesv3ndwarves** [comment]
Interesting. Thankyou for that.

**Comment by LiJT** [comment]
despite the licensing: "for research only"
https://github.com/ubisoft/ComfyUI-Chord
I think we should instead use this one to generate far better normal map

**Comment by Snoiteandthesv3ndwarves** [comment]
Note: It does not appear to be available for Mac.

**Comment by foxofthedead001-arch** [comment]
@HugoTini i have recently installed the latest update for blender {5.1.0}, when i wanted to install your addon i was greeted with a message that says, "Dependency install Error" can you update the addon to be capable for Blender 5.1? Thanks

**Comment by InboundGodz** [comment]
This bump does fix the dependency download issue on Blender for 5.1.
If any dont want to bother with doing the changes, attached are the Dependency files. That just need to be moved to: 
"C:\Users\[YourUser]\AppData\Roaming\Blender Foundation\Blender\5.1\scripts\addons\DeepBump-8".

Google Drive: https://drive.google.com/drive/folders/1P2HG0CbIf6zna6OefyTIE1Mn-5MSge3E?usp=sharing

**Comment by perception5** [comment]
> This bump does fix the dependency download issue on Blender for 5.1. If any dont want to bother with doing the changes, attached are the Dependency files. That just need to be moved to: "C:\Users[YourUser]\AppData\Roaming\Blender Foundation\Blender\5.1\scripts\addons\DeepBump-8".
> 
> Google Drive: https://drive.google.com/drive/folders/1P2HG0CbIf6zna6OefyTIE1Mn-5MSge3E?usp=sharing

Thanks brother, the download took a while to zip, but it's working flawlessly.
