### ISSUE TITLE
Can't install dependencies

### ISSUE THREAD

**Issue by stotka1** [HugoTini/DeepBump#46]
4.0.2 Blender getting this error message when trying to install ![Image](https://github.com/user-attachments/assets/e5e2b0df-e728-4e49-a9af-901d45d000a5)

**Comment by daliborturbeki** [comment]
I have the same error, tried uninstalling and running Blender as administrator but same mistake

**Comment by Spitfire502** [comment]
I am experiencing the same issue.

**Comment by SrGrayFox** [comment]
i got the same error, i hope this maybe help

![Image](https://github.com/user-attachments/assets/1d0e47b9-8f4e-4200-a4e1-47fd5b7d0a33)

**Comment by HugoTini** [comment]
Seems similar to https://github.com/microsoft/onnxruntime/issues/16116 . I can confirm this error occurs on windows (but no issues on Linux). Could be related to the Visual C++ Runtime requirement as mentioned here https://onnxruntime.ai/docs/install/ . However even after installing this runtime I still get the error..

**Comment by filiperino** [comment]
Managed to fix it for now. Had to change the version of onnxruntime it pulls in and patch install_and_import_module method to install it.

```py
# Python dependencies management helpers from :
# https://github.com/robertguetzkow/blender-python-examples/tree/master/add_ons/install_dependencies
Dependency = namedtuple('Dependency', ['module', 'package', 'name'])
dependencies = (Dependency(module='onnxruntime==1.15.1', package=None, name='ort'),
                Dependency(module='numpy', package=None, name='np'))
dependencies_installed = False
```

```py
def install_and_import_module(module_name, package_name=None, global_name=None):
    if package_name is None:
        package_name = module_name
    if global_name is None:
        global_name = module_name
    # Install dependency with pip in the addon folder
    print(module_name)
    result = subprocess.run([sys.executable, '-m', 'pip', 'install', package_name, '-t', get_dependencies_path()], 
                            text=True, capture_output=True)
    if result.returncode != 0 :
        raise Exception(f'Dependency install issue : {result}') 

    # The installation succeeded, attempt to import the module again
    import_module(module_name.split("==")[0], global_name)
```

**Comment by stotka1** [comment]
Where do I input this? I'm not familiar with coding blender

**Comment by filiperino** [comment]
> Where do I input this? I'm not familiar with coding blender

the code that i modified resides in `__init__.py`, path to the file (on my PC) is `C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\DeepBump-7\__init__.py`

**Comment by HugoTini** [comment]
@filiperino Thanks for looking into this, downgrading to `onnxruntime==1.15.1` unfortunately gives me a new error (on linux): 

    cannot import name 'cuda_version' from 'onnxruntime.capi.onnxruntime_validation'

(which makes no sense since we are only using the cpu version of onnxruntime, and there is no cuda lib / nvidia gpu on the device I'm using)

**Comment by stotka1** [comment]
got this now. ![Image](https://github.com/user-attachments/assets/f587ac8e-0f3d-49ad-9d32-1dd5c43196e4)

**Comment by filiperino** [comment]
> [@filiperino](https://github.com/filiperino) Thanks for looking into this, downgrading to `onnxruntime==1.15.1` unfortunately gives me a new error (on linux):
> 
> ```
> cannot import name 'cuda_version' from 'onnxruntime.capi.onnxruntime_validation'
> ```
> 
> (which makes no sense since we are only using the cpu version of onnxruntime, and there is no cuda lib / nvidia gpu on the device I'm using)

maybe newer versions work? 1.16.0 and up, just not the latest runtime, worth checking out.

**Comment by filiperino** [comment]
> got this now. ![Image](https://github.com/user-attachments/assets/f587ac8e-0f3d-49ad-9d32-1dd5c43196e4)

Shouldn't happen. try uninstalling fully then patching the code. If the issue persists, send the log from Window -> System Console.

**Comment by HugoTini** [comment]
Actually seems to work now with  `1.15.1`, I have published a [new release](https://github.com/HugoTini/DeepBump/releases/tag/v8), let's see if this fixes the issue

**Comment by filiperino** [comment]
> Actually seems to work now with `1.15.1`, I have published a [new release](https://github.com/HugoTini/DeepBump/releases/tag/v8), let's see if this fixes the issue

Thank you!

**Comment by HugoTini** [comment]
I have tested the v8 release on Linux + Win10 + Win11 and it works on all of them. Thanks again @filiperino for looking into it!

I'm closing the issue, but if there is still any problem feel free to reopen an issue

**Comment by nicomy** [comment]
Hello there ! 

Thank you for our work ! 
I have the same problem with windows 10. 

The version of onnxruntime is 1.21.1 and may have a problem. 

It seems to work with the version 1.15.1. 
I have edited `_init__.py` of DeepBump as mentionned by @filiperino 
```python
# Python dependencies management helpers from :
# https://github.com/robertguetzkow/blender-python-examples/tree/master/add_ons/install_dependencies
Dependency = namedtuple('Dependency', ['module', 'package', 'name'])
dependencies = (Dependency(module='onnxruntime', package='onnxruntime==1.15.1', name='ort'),
                Dependency(module='numpy', package=None, name='np'))
dependencies_installed = False

```

Thank you

**Comment by LeoRacing77** [comment]
Just in case this helps someone, in my case I had to change the _init__.py file previous to install the script and then it worked

**Comment by LLRA** [comment]
For anyone checking this thread in 2026 - changing the version to 1.20.1 fixes the error now!
